version: "3.8"

services:
  marker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
    environment:
      HUGGINGFACE_TOKEN: ${HUGGINGFACE_TOKEN}
